remote_theme: just-the-docs/just-the-docs
title: "Hello, I'm Lionel Seoane"
description: "My personal website"
color_scheme: dark 
search_enabled: true
aux_links:
  "GitHub Repository": "https://github.com/lioseoane/lioseoane.github.io"
nav_order: 1
has_children: true