remote_theme: daviddarnes/garth
title: "Hello, I'm Lionel Seoane"
description: "My personal website"
baseurl: ""  # Keep this empty unless using a subdirectory
url: "https://lioseoane.github.io"  # Your GitHub Pages URL

# Author information
author:
  name: "Lionel Seoane"
  email: "your-email@example.com"
  twitter_username: "lioseoane"
  github_username: "lioseoane"

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Enable GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
