remote_theme: pmarsceill/just-the-docs
title: "Hello, I'm Lionel Seoane"
description: "My personal website"
baseurl: ""  # Keep this empty unless using a subdirectory
url: "https://lioseoane.github.io"  # Your GitHub Pages URL

# Author information
author:
  name: "Lionel Seoane"
  email: "your-email@example.com"
  twitter_username: "lioseoane"
  github_username: "lioseoane"

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Enable GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Just-the-Docs options (see full list at https://github.com/pmarsceill/just-the-docs)
just_the_docs:
  # enable built-in search
  search_enabled: true

  # top nav items
  nav:
    - title: "Home"
      url: /
    - title: "Blog"
      url: /blog/
    - title: "Projects"
      url: /projects/
    - title: "Resume"
      url: /resume/

  # your logo (optional)
  logo:
    image: /assets/images/logo.png
    alt: "Lionel Seoane"
